apiVersion: v1
kind: Pod
metadata:
  name: hackme-app
  labels:
    app: hackme-app
spec:
  containers:
    - name: app
      image: ldynia/hackme-app:v2
      ports:
        - containerPort: 80
          protocol: TCP